from django.db import models
from django.db.models.signals import post_save #BR:Not sure when to use postsave

class User(models.Model):#BR:User Persistent Data
	flag = models.BooleanField(default=True)
	id = models.CharField(max_length=255, unique = True, primary_key=True)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	status = models.IntegerField(default=0,help_text=u"Number of status points accumulated")
	coins = models.IntegerField(default=0,help_text=u"Amount of game currency accumulated")	

	def __unicode__(self):
		return self.first_name + " " + self.last_name

class Game_History(models.Model):
	#BR:Primary key will be autogenerated
	flag = models.BooleanField(default=True)
	user_id = models.ForeignKey('User')
	session_time = models.DateTimeField()
	question_id = models.ForeignKey('Question')
	answer_time = models.DateTimeField()

	def __unicode__(self):
		return self.user_id + " - " + self.session_time

class Path(models.Model):
	#BR:Primary key will be autogenerated
	flag = models.BooleanField(default = True)
	gameHistory_id = models.ForeignKey('Game_History')
	question_id = models.ForeignKey('Question')
	pageload_time = models.DateTimeField()
	url = models.CharField(max_length=255)
	page_source = models.TextField()
	#BR: page source can't be stored in 255 chars	

	def __unicode__(self):
		return self.url

class Question(models.Model):
	flag = models.BooleanField(default=True)
	active = models.BooleanField(default=True)
	#BR:id = models.CharFields(max_length=255,unique=True)#Primary key autogenerated
	text = models.CharField(max_length=255,unique=True)
	answer = models.CharField(max_length=255, unique=True)
	answer_format = models.CharField(max_length=255, unique=True)
	answer_url = models.CharField(max_length=255, unique=True)
	user_id = models.ForeignKey('User')
	rating = models.CharField(max_length=255,)
	num_rating = models.IntegerField(blank=True,null=True)
	difficulty = models.IntegerField(blank=True,null=True)

	def __unicode__(self):
		return self.text		
  

